version: '3'

services:
    upload:
        build: .
        ports:
            - 80:5000
        volumes:
            - ./data:/data
        environment:
            HOST: "localhost"
            TOKEN: default-token